const BrandsData = [
  {
    id: 1,
    img: require("../../assets/brands/iphone/iphone1.png"),
    name: "iphone X",
    category: "iphone",
    price: 10_000_000,
  },
  {
    id: 2,
    img: require("../../assets/brands/iphone/iphone2.jpg"),
    name: "iphone XS MAX",
    category: "iphone",
    price: 15_000_000,
  },
  {
    id: 3,
    img: require("../../assets/brands/iphone/iphone3.jpg"),
    name: "iphone 5",
    category: "iphone",
    price: 8_000_000,
  },
  {
    id: 4,
    img: require("../../assets/brands/iphone/iphone4.jpg"),
    name: "iphone 8 Pro",
    category: "iphone",
    price: 14_000_000,
  },
  {
    id: 5,
    img: require("../../assets/brands/iphone/iphone5.jpg"),
    name: "iphone 14",
    category: "iphone",
    price: 50_000_000,
  },
  {
    id: 6,
    img: require("../../assets/brands/iphone/iphone6.jpg"),
    name: "iphone 14 Pro",
    category: "iphone",
    price: 60_000_000,
  },
  {
    id: 7,
    img: require("../../assets/brands/samsung/samsung1.png"),
    name: "samsung Galaxy s5",
    category: "samsung",
    price: 20_000_000,
  },
  {
    id: 8,
    img: require("../../assets/brands/samsung/samsung2.png"),
    name: "samsung Galaxy s10 plus",
    category: "samsung",
    price: 40_000_000,
  },
  {
    id: 9,
    img: require("../../assets/brands/samsung/samsung3.png"),
    name: "samsung Galaxy s8",
    category: "samsung",
    price: 15_000_000,
  },
  {
    id: 10,
    img: require("../../assets/brands/samsung/samsung4.png"),
    name: "samsung 5",
    category: "samsung",
    price: 8_000_000,
  },
  {
    id: 11,
    img: require("../../assets/brands/asus/asus1.png"),
    name: "asus 5Xi",
    category: "asus",
    price: 85_000_000,
  },
  {
    id: 12,
    img: require("../../assets/brands/asus/asus2.png"),
    name: "asus 4D23",
    category: "asus",
    price: 20_000_000,
  },
  {
    id: 13,
    img: require("../../assets/brands/lenovo/lenovo1.png"),
    name: "lenovo i3",
    category: "lenovo",
    price: 36_000_000,
  },
  {
    id: 14,
    img: require("../../assets/brands/lenovo/lenovo2.jpg"),
    name: "lenovo 5s",
    category: "lenovo",
    price: 12_000_000,
  },
  {
    id: 15,
    img: require("../../assets/brands/lenovo/lenovo3.png"),
    name: "lenovo 48DR",
    category: "lenovo",
    price: 8_000_000,
  },
  {
    id: 14,
    img: require("../../assets/brands/lenovo/lenovo4.png"),
    name: "lenovo FG2",
    category: "lenovo",
    price: 43_000_000,
  },
];

export default BrandsData;
