const amazingDatas = [
  {
    id: 1,
    discount: 50,
    img: require("../../assets/images/flash/flash-1.png"),
    name: "Shoes",
    price: 100000,
    qty: 0,
  },
  {
    id: 2,
    discount: 40,
    img: require("../../assets/images/flash/flash-2.png"),
    name: "Watch",
    price: 300000,
    qty: 0,
  },
  {
    id: 3,
    discount: 40,
    img: require("../../assets/images/flash/flash-3.png"),
    name: "Smart Mobile Black",
    price: 200000,
    qty: 0,
  },
  {
    id: 4,
    discount: 40,
    img: require("../../assets/images/flash/flash-4.png"),
    name: "Smart Watch Black",
    price: 500000,
    qty: 0,
  },
  {
    id: 5,
    discount: 50,
    img: require("../../assets/images/flash/flash-1.png"),
    name: "Shoes",
    price: 100000,
    qty: 0,
  },
  {
    id: 6,
    discount: 50,
    img: require("../../assets/images/flash/flash-3.png"),
    name: "Shoes",
    price: 100000,
    qty: 0,
  },
  {
    id: 7,
    discount: 50,
    img: require("../../assets/images/flash/flash-1.png"),
    name: "Shoes",
    price: 100000,
    qty: 0,
  },
  {
    id: 8,
    discount: 40,
    img: require("../../assets/images/flash/flash-2.png"),
    name: "Watch",
    price: 20000,
    qty: 0,
  },
  {
    id: 9,
    discount: 40,
    img: require("../../assets/images/flash/flash-3.png"),
    name: "Smart Mobile Black",
    price: 200000,
    qty: 0,
  },
];

export default amazingDatas;